### ISSUE TITLE
download SHA256SUMS.asc 404 not found

### ISSUE THREAD

**Issue by ghost** [dashpay/dashcore-node#9] opened 2017-02-02 10:40 UTC
Quits at checksum verification when running bitcore-node-dash create, checksum file not found.

**Comment by snogcel** [comment] 2017-02-03 04:39
Thanks for reporting this, I just ran a test on the latest npm package (v3.0.3) and was not able to reproduce. What you seem to be running into is a verification method (https://github.com/dashpay/bitcore-node-dash/blob/master/scripts/download#L65-L88) though I'm not entirely clear on why it's being triggered.

For reference, the commands I issued a few moments ago:

npm install -g bitcore-node-dash
bitcore-node-dash create -d ~/.bitcore/data mynode

This downloaded the binary from bamboo twice, however in neither case did it verify the download. Can you provide additional info on your OS / Node Version as well as the commands issued to reproduce the issue?

**Comment by snogcel** [comment] 2017-02-03 14:33
After some troubleshooting we identified that the issue related to various NodeJS dependencies. Though not always necessary, NVM typically solves these types of issues: https://github.com/creationix/nvm#install-script. Closing issue.

**Closed as completed by snogcel** 2017-02-03 14:33 UTC
